image: node:10.15.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm run build
            - scp -r dist/* ubuntu@52.72.101.212:/var/www/html