name: Node.js Build and Push

on:
  push:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - run: npm install
      - run: npm run build
      
      - name: Copy Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.TERM_HOST }}
          username: ${{ secrets.TERM_USERNAME }}
          port: ${{ secrets.TERM_PORT }}
          key: ${{ secrets.TERM_PRIVATE }}
          source: "dist/*"
          target: "/var/www/html"
